sudo: required
dist: bionic
language: c++

os:
  - linux

compiler:
  - gcc

env:
  global:
   - YARP_BRANCH="master"
   - ICUBcontrib_DIR="icub-contrib-common/build/lib/ICUBcontrib"

install:
  # ubuntu dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh -c 'echo "deb http://www.icub.org/ubuntu `lsb_release -cs` contrib/science" > /etc/apt/sources.list.d/icub.list'; fi
  # icub key
  - sudo apt-get install build-essential git cmake cmake-curses-gui libeigen3-dev libace-dev libedit-dev libsqlite3-dev libtinyxml-dev
      
    # install ycm
  - git clone https://github.com/robotology/ycm.git -b v0.11.3
  - cd ycm
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - sudo make install
  - cd ../..
  
    # install yarp
  - git clone https://github.com/robotology/yarp.git -b v3.4.0
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer:BOOL=ON
  - make -j2
  - sudo make install
  - cd ../..
  
  # install icub
  - git clone https://github.com/robotology/icub-main.git -b v1.17.0
  - cd icub-main
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install -j
  - cd ../../

  # install icub-contrib-common from master
  - git clone --depth 1 https://github.com/robotology/icub-contrib-common.git
  - cd icub-contrib-common
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install -j
  - cd ../../
  
  # install opencv 
  - sudo apt install python3-opencv
  - echo "OpenCV installed."

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j

after_success:
