sudo: required
dist: trusty
language: c++

os:
  - linux

compiler:
  - gcc

env:
  global:
   - YARP_BRANCH="master"
   - ICUBcontrib_DIR="icub-contrib-common/build/lib/ICUBcontrib"

install:
  #ubuntu dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --assume-yes --force-yes install cmake libeigen3-dev icub-common libv4lconvert0 libv4l-dev; fi
  
  #install yarp from master
  - git clone --depth 1 -b $YARP_BRANCH https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer_carrier:BOOL=ON
  - make -j
  - sudo make install
  - cd ../..
  
  #install icub from master
  - git clone --depth 1 https://github.com/robotology/icub-main.git
  - cd icub-main
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - sudo make install -j
  - cd ../../

  #install icub-contrib-common from master
  - git clone --depth 1 https://github.com/robotology/icub-contrib-common.git
  - cd icub-contrib-common
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install -j
  - cd ../../


before_script:
  - mkdir GIVER-RECEIVER_MOD-ARM-DIFF/real/build
  - cd GIVER-RECEIVER_MOD-ARM-DIFF/real/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j
  - cd ../../..

  - mkdir GIVER-RECEIVER_MOD-ARM-DIFF/sim/build
  - cd GIVER-RECEIVER_MOD-ARM-DIFF/sim/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j
  - cd ../../..

  - mkdir MASTER-SLAVE_PROX-HEIGHT/real/build
  - cd MASTER-SLAVE_PROX-HEIGHT/real/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j
  - cd ../../..

  - mkdir MASTER-SLAVE_PROX-HEIGHT/sim/build
  - cd MASTER-SLAVE_PROX-HEIGHT/sim/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j

script:


after_success:

